---
- name: Get a non existent attribute from an object that does exist
  hosts: localhost
  connection: local
  vars:
  - object: root

  gather_facts: False
  roles:
  - syncrou.manageiq-automate

  tasks:
    - name: "Get novar attribute from root object"
      manageiq_automate:
        workspace: "{{ workspace }}"
        get_attribute:
          object: "root"
          attribute: "novar"
      register: noobject
