---
- name: Get attribute from a non existent object  
  hosts: localhost
  connection: local
  vars:
  - object: root

  gather_facts: False
  roles:
  - syncrou.manageiq-automate

  tasks:
    - name: "Get missing attribute from non existent object"
      manageiq_automate:
        workspace: "{{ workspace }}"
        get_attribute:
          object: "noroot"
          attribute: "missing"
      register: missing
