---
# This playbook uses a host group and then connects using winrm 
# - name: Echo Hello, world!
- hosts: all
  # connection: winrm
  tasks:
  - debug: msg="Hello, world! localhost"

# This playbook step uses the win_ping module to test connectivity to Windows host group called win
- hosts: win

  tasks:
  - name: "Wait for connection to VM"
    wait_for_connection:
      timeout: 300

  - win_ping:
